DATA_PROVIDER: gemini
TRADE_PROVIDER: gemini
SYMBOLS: ["BTC-GUSD-PERP","ETH-GUSD-PERP","SOL-GUSD-PERP","DOGE-GUSD-PERP"]
PRICE_DEV: 0.01
VOL_MULT: 3
LLM_CONF: 0.65
MAX_GROSS_PCT_EQUITY: 0.25
MAX_LEVERAGE: 3
STOP_LOSS_PCT: 0.01
COOLDOWN_HR: 6
OPENAI_MODEL: gpt-4o-mini
PROVIDERS:
  gemini:
    API_KEY: ""
    API_SECRET: ""
    WS_URL: wss://api.gemini.com/v2/marketdata
    REST_URL: https://api.gemini.com
  alpaca: 
    API_KEY: ""
    API_SECRET: ""