DATA_PROVIDER: gemini
TRADE_PROVIDER: gemini
SYMBOLS: ["BTC-GUSD-PERP","ETH-GUSD-PERP","SOL-GUSD-PERP","DOGE-GUSD-PERP"]
PRICE_DEV: 0.01
VOL_MULT: 3
LLM_CONF: 0.65
MAX_GROSS_PCT_EQUITY: 0.25
MAX_LEVERAGE: 3
STOP_LOSS_PCT: 0.01
COOLDOWN_HR: 6
OPENAI_MODEL: gpt-4o-mini

# Backtesting Configuration
BACKTEST:
  INITIAL_EQUITY: 100000
  SLIPPAGE_BPS: 5          # 5 basis points slippage
  FEE_BPS: 8               # 8 basis points trading fees
  START_DATE: "2023-01-01"
  END_DATE: "2024-12-31"
  OUT_OF_SAMPLE_START: "2025-01-01"
  TRAIN_RATIO: 0.7         # 70% for training, 30% for testing
  STEP_SIZE_DAYS: 30       # Walk-forward step size
  TARGET_SHARPE: 1.3       # Target Sharpe ratio
  TARGET_MAX_DD: 8.0       # Target maximum drawdown %

PROVIDERS:
  gemini:
    API_KEY: ""
    API_SECRET: ""
    WS_URL: wss://api.gemini.com/v2/marketdata
    REST_URL: https://api.gemini.com
    HISTORICAL_URL: https://api.gemini.com/v1/candles
  alpaca: 
    API_KEY: ""
    API_SECRET: ""